### ISSUE TITLE
Enable Longlines Mode

### ISSUE THREAD

**Issue by grossbart** [technomancy/emacs-starter-kit#1]
What do you think, couldn't an enabled `longlines-mode` be a sensible default for the starter kit? I was just editing a LaTeX document and it became pretty annoying to go through the longer lines of my text and I had to do some research on how to get this right in Emacs.

As far as I understand, this is a minor mode that would have to be enabled by a hook. Maybe there is a global hook or something, that would enable it for every buffer, so this works like in every other text editor…
- http://www.gnu.org/software/emacs/manual/html_node/emacs/Longlines.html
- http://abstractfactory.blogspot.com/2008/06/soft-word-wrap-for-long-lines-wednesday.html

**Comment by technomancy** [comment]
I don't think this is a good idea for every mode, but it would be a good candidate for a text-mode hook.

**Comment by grossbart** [comment]
You're right, I had some code open today with the `longlines-mode` on and it didn't show the line breaks anymore, which felt strange. But hooking into text-mode would be perfect, I think.

**Comment by technomancy** [comment]
Actually I realized I already have auto-fill-mode turned on in a text-mode hook... I think auto-fill-mode makes more sense for things like readmes and such, so I don't think I'm going to change the hook in my starter kit... It would be easy to change in your fork though.
