### ISSUE TITLE
Can I specify my own cperl-mode?

### ISSUE THREAD

**Issue by j1n3l0** [technomancy/emacs-starter-kit#10]
Hi,

Is it possible to use a different cperl-mode than the one you've added in ~/.emacs.d/elpa-to-submit? I would prefer to use this version http://github.com/jrockway/cperl-mode (it has some more features not in the main cperl-mode). I have tried copying this version into ~/.emacs.d/elpa-to-submit and restarting emacs but that does not seem to work.

What gives? Is there something else I ought to be doing?

Thanks

**Comment by technomancy** [comment]
Please contact the author of cperl-mode and ask him to submit it as an ELPA package. Once it's in ELPA, I will remove it from elpa-to-submit and you can install it that way.
