### ISSUE TITLE
Don't hardcode magit version

### ISSUE THREAD

**Issue by dakrone** [technomancy/emacs-starter-kit#100]
ESK has magit hardcoded at 0.8.1, I don't mind the newer versions, but it's a pain to try and change the version that ESK will let me install.

Is there a way I can install whatever version of magit I'd like? (1.0.0 in my case)

**Comment by technomancy** [comment]
The dependency that the starter kit declares is only a "at least this version" rather than locked to a specific version. It picks up the latest version when I install here; does it not to the same for you?

**Comment by dakrone** [comment]
You're correct, this works for me. Sorry, my mistake.
