### ISSUE TITLE
Starter kit loads packages instead of config files

### ISSUE THREAD

**Issue by eoranged** [technomancy/emacs-starter-kit#113]
If you have `python` package installed and have `~/.emacs.d/username/python.el`, then package will be loaded instead of config file:

```
Loading /home/eoranged/.emacs.d/eoranged.el (source)...done                                                     
Loading /home/eoranged/.emacs.d/eoranged/bindings.el (source)...done                                            
Loading /home/eoranged/.emacs.d/eoranged/lua.el (source)...done                                               
...
Loading /home/eoranged/.emacs.d/eoranged/markdown.el (source)...done                                            
Loading /home/eoranged/.emacs.d/eoranged/postgres.el (source)...done                                            
Loading /home/eoranged/.emacs.d/elpa/python-20111118/python.el (source)...done                                  
For information about GNU Emacs and the GNU system, type C-h C-a.                     
```

but if you'll rename python.el to python2.el everything works fine.  

Looks like the problem is command `(mapc 'load (directory-files esk-user-dir nil "^[^#].*el$"))` from starter-kit.el which doesn't perform concatenation of path and file name.
For now I've just renamed my config and everything looks great, but I don't feel good about.
The only solution I've found is to wrap `load` function, but it looks spiky for me. I suspect that if config dir will be added to the beginning of load-path,than everything will be ok, but not sure.

**Comment by technomancy** [comment]
This is just how the load path works. If you put something on the load path with the same name as an existing file, it will shadow it. It's not specific to the starter kit.
