### ISSUE TITLE
void-function idle-highlight

### ISSUE THREAD

**Issue by HarryGuerrilla** [technomancy/emacs-starter-kit#12]
I'm running emacs 23.1.5 compiled from source for Max OS 10.5.8.

I checked out the latest emacs-starter-kit from github and get the following error:

Debugger entered--Lisp error: (void-function idle-highlight)
  (idle-highlight 1)
  (lambda nil (paredit-mode 1) (idle-highlight 1) (run-coding-hook))()
  run-hooks(emacs-lisp-mode-hook lisp-interaction-mode-hook)
  apply(run-hooks (emacs-lisp-mode-hook lisp-interaction-mode-hook))
  run-mode-hooks(lisp-interaction-mode-hook)
  lisp-interaction-mode()
  command-line()
  normal-top-level()

When I use an earlier version of the emacs-starter-kit, I do not get this error.

Any help would be greatly appreciated.

**Comment by technomancy** [comment]
This is probably coming from an ELPA bug. Can you delete the ~/.emacs.d/elpa directory and restart Emacs? The idle-highlight function is provided by an elpa package, not by the starter kit itself.

**Comment by emaxerrno** [comment]
i get something similar:

package: idle-highlight not available for installation.
