### ISSUE TITLE
Unable to globally disable hl-line-mode

### ISSUE THREAD

**Issue by bitops** [technomancy/emacs-starter-kit#122]
I realize that it's a bit ridiculous to file an issue for this but I've tried a lot of different things without success.

In the starter kit, and those for ruby and lisp, hl-line-mode is enabled by default. I prefer it off, but have found nothing that will disable it globally for all files. I've been reduced to M-x hl-line-mode in every buffer I open.

Is there a way to do this?

**Comment by technomancy** [comment]
You should be able to use this:

(remove-hook 'prog-mode-hook 'esk-turn-on-hl-line-mode)

**Comment by bitops** [comment]
Ah, thank you so much! That was the one permutation of 'remove-hook' that no-one had mentioned yet.

Thanks again.
