### ISSUE TITLE
.el files in the userdir are being put in the load-path

### ISSUE THREAD

**Issue by ghost** [technomancy/emacs-starter-kit#126]
The .el files in ~/.emacs.d/<username>/ are automatically loaded at the startup.
Is there any use of also putting them in the load-path?

For example, the file `tex.el` would "win" over the AuCTeX-mode's `tex.el` and break the TeX support.

**Comment by DarwinAwardWinner** [comment]
The main use would probably be easily reloading them after editing.

**Comment by mamciek** [comment]
after the patch emacs complains that "mapc: Cannot open load file" any file placed in the esk-user-dir

**Comment by DarwinAwardWinner** [comment]
The convention that I've used in my personal emacs config (not ESK-based) is to have all of my settings files be named `[PACKAGE]-settings.el`. That way there is never any naming conflict.
