### ISSUE TITLE
comments are broken into multiple lines

### ISSUE THREAD

**Issue by tommy24** [technomancy/emacs-starter-kit#127]
Hi,

When I comment out a long line using C-; , it will automatically break the line into several lines.
This alters the format that I setted before.
I only have this issue when I use emacs 24 with starter kit.
Any idea how to disable this feature?
Thanks.

Tommy

**Comment by sluukkonen** [comment]
It's called [Auto Fill Mode](http://www.gnu.org/software/emacs/manual/html_node/emacs/Auto-Fill.html). One way to disable it would be to add the following hook to C mode:

```
(add-hook 'c-mode-hook
      (lambda ()
        (auto-fill-mode 0)))
```

**Comment by tommy24** [comment]
Thanks a lot. It works as I expected now.
