### ISSUE TITLE
emacsclient complains about files are not saved when I try to close it

### ISSUE THREAD

**Issue by tommy24** [technomancy/emacs-starter-kit#128]
Hi,

Is it possible to disable the warning messages about some files are not saved?
It is quite annoying since everytime I exit emacsclient, the warning messages ask me whether I want to save some files or not.
The only way to avoid those messages are pressing 'y' to save the file. Pressing 'n' seems useless, next time when you exit, the same warning shows up again. Usually I save files a lot whenever I make any changes and want them to be saved. If the files are left without saving, I usually don't want them to be saved. Is there anyway to disable those warning messages? Or at least when I pressed 'n' to not save it, it won't show up again.
Thanks.

Tommy

**Comment by DarwinAwardWinner** [comment]
I don't think this has anything to do with ESK, unless some setting in ESK causes this to happen. Regardless, check the value of `delete-frame-functions`. See if there's a function in that hook that prompts for saving files.

**Comment by technomancy** [comment]
Yeah, this is unrelated, sorry.
