### ISSUE TITLE
Strange tramp related errors

### ISSUE THREAD

**Issue by mguterl** [technomancy/emacs-starter-kit#13]
The first time I open any ruby file I get an error.  This only occurs the first time I'm opening a file.

Debugger entered--Lisp error: (void-function tramp-list-remote-buffers)
  (tramp-list-remote-buffers)
  (subsetp (list (current-buffer)) (tramp-list-remote-buffers))
  (not (subsetp (list ...) (tramp-list-remote-buffers)))
  (and buffer-file-name (file-writable-p (file-name-directory buffer-file-name)) (file-writable-p buffer-file-name) (not (subsetp ... ...)))
  (if (and buffer-file-name (file-writable-p ...) (file-writable-p buffer-file-name) (not ...)) (progn (local-set-key ... ...) (flymake-mode t)))
  (when (and buffer-file-name (file-writable-p ...) (file-writable-p buffer-file-name) (not ...)) (local-set-key (kbd "C-c d") (quote flymake-display-err-menu-for-current-line)) (flymake-mode t))
  (lambda nil (when (and buffer-file-name ... ... ...) (local-set-key ... ...) (flymake-mode t)))()
  run-hooks(ruby-mode-hook)
  apply(run-hooks ruby-mode-hook)
  run-mode-hooks(ruby-mode-hook)
  ruby-mode()
  set-auto-mode-0(ruby-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer candidate_spec.rb> "~/code/rm/main/spec/models/candidate_spec.rb" nil nil "~/code/rm/main/spec/models/candidate_spec.rb" (32645779 234881026))
  find-file-noselect("/Users/michaelguterl/code/rm/main/spec/models/candidate_spec.rb" nil nil)
  ido-file-internal(raise-frame)
  ido-find-file()
  call-interactively(ido-find-file)

**Comment by mguterl** [comment]
I was receiving this error while using CarbonEmacs on OS 10.6.  I just installed the emacs-app port from Macports, that is based on 23.1 and the error has gone away.

**Comment by colbell** [comment]
Under Emacs 23.1.50.1 (Ubuntu 9.04) I needed to do a (require 'tramp-cmds) to stop this error.

**Comment by jmhodges** [comment]
Yeah, seeing this on OS X 10.5 with Emacs 23.1. colbell's (require 'tramp-cmds) does fix the problem.

**Comment by smerritt** [comment]
I think this is fixed by http://github.com/technomancy/emacs-starter-kit/commit/f263f8e5a9b5f539984d8f8076b7d2f3186274bd.

**Comment by mguterl** [comment]
Closed.

**Comment by technomancy** [comment]
closing
