### ISSUE TITLE
emacs complains that "mapc: Cannot open load file" any file placed in the esk-user-dir

### ISSUE THREAD

**Issue by eoranged** [technomancy/emacs-starter-kit#135]
After [640e71c96dc709440a0b47e7604469888831b5ee](https://github.com/technomancy/emacs-starter-kit/commit/640e71c96dc709440a0b47e7604469888831b5ee) emacs is unable to load any file from userdir.
Reverting the patch fixes the problem.
I'm running latest emacs and starter kit from git (starter kit is installed via MELPA).

**Comment by genedelisa** [comment]
Verified eoranged's description.

I have starter-kit-20120504
I have my mode specific setup files here. Until I upgraded to this release it worked fine.

I added
  (add-to-list 'load-path esk-user-dir)
to starter-kit-autoloads.el and it works again.

**Comment by eoranged** [comment]
Can be fixed by replacing

```
  (when (file-exists-p esk-user-dir)
    (mapc 'esk-load (directory-files esk-user-dir nil "^[^#].*el$"))))))
```

with 

```
  (when (file-exists-p esk-user-dir)
    (mapc 'esk-load (directory-files esk-user-dir t "^[^#].*el$"))))))
```

in starter-kit.el

The problem is caused by first optional parameter for `directory-files`, which makes one return filenames without path, so load tries to find this files in load-path. But we removed `esk-user-dir` from load path!

I'm upset that the problem is exists about two month in starter kit and still not fixed.  
@technomancy , please take look.

**Comment by technomancy** [comment]
Calm down; it hasn't been noticed because there hasn't been a release since December and nobody runs from source.

**Comment by eoranged** [comment]
@technomancy sorry for being impolite here, emacs is quite stressful thing at the beginig :)

And thanks a lot for good starting point for using emacs. ESK was really helpful there.
Actually, this thing bug motivated me to start learning elisp and now my Emacs compatible with good IDEs. 

Keep going with the project!
