### ISSUE TITLE
Where can I report bugs for starter-kit-ruby ?

### ISSUE THREAD

**Issue by letronje** [technomancy/emacs-starter-kit#137]

**Comment by letronje** [comment]
<TAB>Indentation gone wrong for lines after 'lines with symbols ending with "=" '  
Screenshot @ http://i.imgur.com/BWhEK.png

**Comment by smerritt** [comment]
For starter-kit-ruby bugs, you can report them here and I'll take a look.

However, the problem you're having with indentation looks like a problem with ruby-mode itself, not with anything that the starter kit provides.

**Comment by letronje** [comment]
Any idea who maintains ruby-mode ?

**Comment by technomancy** [comment]
ruby-mode is part of GNU Emacs now.
