### ISSUE TITLE
progn: Symbol's value as variable is void: eshell-output-filter-functions (on emacs-snapshot)

### ISSUE THREAD

**Issue by sinewalker** [technomancy/emacs-starter-kit#146]
Have not nutted the actual problem down yet, but I noticed after updating emacs-snapshot package on my Debian box that M-x eshell fails with this message:

progn: Symbol's value as variable is void: eshell-output-filter-functions

If I uninstall the starter-kit-eshell package and restart emacs, it all works fine (but without the tweaks, of course).  It also works fine on emacs24 stable.

I noticed on the Savanna log that they are jiggering around with eshell's library layout or something, which could be causing a clash with this module, somehow.  Sorry my elisp is very rudimentary still or I'd try and debug for you. Happy to help though.

Version details are:
emacs-snapshot   2:20120728-1+squeeze  (from Julien Danjou's repository http://emacs.naquadah.org stable/ Packages )
starter-kit-eshell    20120316  (from marmalade.org)

**Comment by zzj** [comment]
I have the exactly the same issue.

**Comment by auser** [comment]
Me too...
