### ISSUE TITLE
Setting proxy on EmacsW32 when using emacs-starter-kit

### ISSUE THREAD

**Issue by cristobalito** [technomancy/emacs-starter-kit#15]
I'm behind a proxy and when trying to install the emacs-starter-kit, I get the warnings (errors) below. Does anyone  know how I can resolve this?

Thanks, 

Chris

_Warnings_

Warning (initialization): An error occurred while loading `c:/Documents and Settings/xxx/Application Data/.emacs.d/init.el':

File error: make client process failed, connection timed out, :name, tromey.com, :buffer, #<killed buffer>, :host, tromey.com, :service, 80, :nowait, nil

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
# The output in my _Messages_ buffer is:

Adding d:/Emacs/EmacsW32/lisp/ to load-path
Loading c:/Documents and Settings/xxx/Application Data/.emacs.d/elpa-to-submit/nxhtml/autostart.el (source)...
Nxml/Nxhtml Autostart.el loading ...
Loading c:/Documents and Settings/xxx/Application Data/.emacs.d/elpa-to-submit/nxhtml/nxhtml-loaddefs.el (source)...done
Loading c:/Documents and Settings/xxx/Application Data/.emacs.d/elpa-to-submit/nxhtml/etc/schema/schema-path-patch.el (source)...done
xhtml-loader.rnc was ok
(No changes need to be saved)
Loading c:/Documents and Settings/xxx/Application Data/.emacs.d/elpa-to-submit/nxhtml/nxhtml/nxhtml-autoload.el (source)...
majmodpri-sort-lists running ...
Loading c:/Documents and Settings/xxx/Application Data/.emacs.d/elpa-to-submit/nxhtml/nxhtml/nxhtml-autoload.el (source)...done
Loading c:/Documents and Settings/xxx/Application Data/.emacs.d/elpa-to-submit/nxhtml/autostart.el (source)...done
# Contacting host: tromey.com:80

**Comment by technomancy** [comment]
On the first launch, Emacs connects to the Internet to install a few packages. On other platforms, you can detect if you are not connected to the Internet and postpone the package installation, but I haven't found a way to do this on Windows yet. Suggestions are welcome.

If you launch Emacs once from a working Internet connection, future launches without a working connection will not be an issue.

**Comment by jhirn** [comment]
I added the following to my init.el near the top to get around this issue:

```
 (setq url-proxy-services '(("no_proxy" . "work\\\\.com")
                       ("http" . "proxy.work.com:911")))
```

Also, if you need to clone this repo be sure to set the variable HTTP_PROXY=proxy.work.com:911 or else you won't be able to hit github on port 80.
