### ISSUE TITLE
ido-find-file confused when cursor over C comment

### ISSUE THREAD

**Issue by mheffner** [technomancy/emacs-starter-kit#16]
If a C-mode buffer contains the text:

/******************************************************************************

inserting the cursor anywhere in the comment and running ido-find-file will try to locate a file named "/******************************************************************************" and fail.

Is this a bug with ido?

**Comment by technomancy** [comment]
It's a quirk of ido-mode; I've run into it myself editing JS files. I'm sure it's possible to work around, but I haven't seen a fix yet. Would love to get a patch for it.

**Comment by DarwinAwardWinner** [comment]
This seems to work for me:

https://github.com/DarwinAwardWinner/dotemacs/blob/master/site-lisp/settings/ffap-settings.el

**Comment by DarwinAwardWinner** [comment]
You can close this now, I guess.
