### ISSUE TITLE
HEAD should point to master instead of v3

### ISSUE THREAD

**Issue by liuweichu** [technomancy/emacs-starter-kit#167]
For some reason, the HEAD is on v3 now, which only contains 3 old files.
A little bit confusing to starters
Maybe it is a mistake? I think it should be master.

**Comment by liuweichu** [comment]
Hmmmm, after a while I realized (guess) maybe the README means the starter kit is deprecated and one should use `better-defaults`?

**Comment by technomancy** [comment]
That's correct; v3 is the latest.
