### ISSUE TITLE
The words 'fix' and 'error' are being highlighted by something from emacs-starter-kit, and I don't know how to turn it off

### ISSUE THREAD

**Issue by kozross** [technomancy/emacs-starter-kit#169]
Basically what the title says. Suppose I have something like this:

(defun foo (x)
    (declare (fixnum x))...

The 'fix' is picked out in an annoying colour, and I can't seem to get rid of it. The same also happens to the word 'error'. How would I turn this off?

**Comment by technomancy** [comment]
You can dig around in the font lock rules, but I would recommend not using the starter kit (or other starter-kit-like things) any more; it's deprecated for exactly this reason. Too many random things thrown together with no documentation.

Take a look at this instead: https://github.com/technomancy/better-defaults/
