### ISSUE TITLE
Error while loading init.el

### ISSUE THREAD

**Issue by bluenote10** [technomancy/emacs-starter-kit#170]
As suggested, I now have a `.emacs.d/init.el` containing only the line:

```
(add-to-list 'package-archives '("marmalade" . "https://marmalade-repo.org/packages/"))
```

When I start Emacs I get:

```
Warning (initialization): An error occurred while loading `/home/<user>/.emacs.d/init.el':

Symbol's value as variable is void: package-archives
```

This seems to be related with [this](http://stackoverflow.com/questions/7287947/adding-marmalade-as-package-source). But since this is my very first experience with Emacs I do not even understand the solution mentioned. Probably not a big issue in general, but rather unfortunate for a starter kit.

I'm running Emacs 24.3.1.

**Comment by technomancy** [comment]
Just fixed this; thanks.
