### ISSUE TITLE
emacs 25: Need package ‘dash-2.12.1’, but only 2.12.0 is available

### ISSUE THREAD

**Issue by hww** [technomancy/emacs-starter-kit#175]
Following installation instruction,  after:

`M-x package-install starter-kit
`
Emacs displays error 

`package-compute-transaction: Need package ‘dash-2.12.1’, but only 2.12.0 is available`

**Comment by technomancy** [comment]
Please don't use the Emacs Starter Kit. If you need something like it, the `better-defaults` package is much better.

Thanks!
