### ISSUE TITLE
Binary plist on Mac OSX

### ISSUE THREAD

**Issue by mtnygard** [technomancy/emacs-starter-kit#19]
I'm getting errors during startup. It appears to be due to osx-plist-update-environment.  It's reading .MacOSX/environment.plist and attempting to parse it as XML.  On my machine (Mac OS 10.5.2), that file is a binary plist, not XML.

Backtrace at http://gist.github.com/233388

**Comment by mtnygard** [comment]
I'm note sure why the file was in the binary plist format.  The following command converts it to XML and let me get past the startup error:

```
plutil -convert xml1 ~/.MacOSX/environment.plist
```

**Comment by technomancy** [comment]
This has since been removed from the starter kit; it's too much of a mess
