### ISSUE TITLE
nXhtml-mode too old

### ISSUE THREAD

**Issue by nolith** [technomancy/emacs-starter-kit#20]
Hi,
i had some problems with the version of nXhtml you provide, when I started typing in a <%= %> on erb.html files emacs starts to hangs.

I've asked on the rinari ml and they suggested me to update nXhtml-mode to 2.01, whit this version I had no problems.

http://groups.google.it/group/emacs-on-rails/browse_thread/thread/460722fbe81585ab

**Comment by lobo-tuerto** [comment]
Yeah, the same happens to me.

**Comment by mguterl** [comment]
Thanks, upgrading fixes the same issue for me.

**Comment by smerritt** [comment]
This issue should be resolved; the starter kit stopped shipping with nxhtml.

http://github.com/technomancy/emacs-starter-kit/commit/2c0ee8268f176343db78ae3f8f9de062f86862d9

**Comment by technomancy** [comment]
Yep, it just became too problematic since it's not well-packaged. If you're using it, you can install it separately and try to bug the maintainer about improving the packaging situation.
