### ISSUE TITLE
ELPA slightly broken in Windows

### ISSUE THREAD

**Issue by jpulakka** [technomancy/emacs-starter-kit#22]
In Windows, there's an issue with ELPA / package.el that causes an error "Local variables entry is missing the suffix" at least when trying to install swank-clojure. A working solution is described here: http://groups.google.com/group/clojure/msg/3b4e04ef9fb0c8bf

**Comment by technomancy** [comment]
Could you reopen as an issue on the package.el project instead? Thanks.

**Comment by jpulakka** [comment]
Ah, there was a separate project for that. Done!
