### ISSUE TITLE
Carbon emacs stutters with *.erb files

### ISSUE THREAD

**Issue by iamwilhelm** [technomancy/emacs-starter-kit#23]
When editing *.erb files, emacs hangs for a little bit, and then goes again, then repeats.  This usually happens when I've been editing for a while.  It's a terrible hamper on productivity.  This only happens with *.erb files.

I'm not sure where to look to debug the problem.  Where do I find the emacs mode that syntax highlights the _.erb?  And how do I turn it off?  Are there other substitutes for *.erb/_.rhtml highlighters?

**Comment by iamwilhelm** [comment]
I think the culprit was flymake.  I was able to turn it off by commenting out the entire section initializing flymake in the ruby section.  Is there a switch to turn it off without commenting out the code?

**Comment by iamwilhelm** [comment]
Well, I spoke too soon.  It's not the flymake.  It still happens.  Is there a way to selectively turn on and off different modules in emacs?  And how do you see what modules have been installed?  That way, I can keep the emacs open, and when it happens, start experimenting with what module causes it.  

It doesn't seem to happen until I have emacs opened for a while, and mostly when I alt-tab windows.  I see the message "not safe backward word" and "not safe forward word" in the messages when it pauses.  I wasn't able to google the phrase and have it come up with anything.  Any suggestions?

**Comment by pjaspers** [comment]
The culprit is the nxhtml/eruby mode, if you use just nxhtml there isn't a problem.

**Comment by mguterl** [comment]
I think this is the same issue which proposes a solution: http://github.com/technomancy/emacs-starter-kit/issues#issue/20

**Comment by pjaspers** [comment]
No I tried that and it still stutters, I've switched to rhtml-mode and now editing views is worry-free again.

**Comment by mguterl** [comment]
@pjaspers - I'm using Emacs 23.1 from http://emacsformacosx.com/, I replaced my ~/.emacs.d/elpa-to-submit/nxhtml directory with the contents of the zip from http://ourcomments.org/Emacs/DL/elisp/nxhtml/zip/nxhtml-2.05-091202.zip

I also ran M-x `recompile-init` but I'm not sure that actually does anything to help this process.

After this, my emacs hasn't stuttered after a couple hours of editing in nxhtml/eruby mode.

**Comment by iamwilhelm** [comment]
How did you end up picking nxhtml-2.05-091202?  I replaced my nxhtml directory with nxhtml-beta 2.07-100201-11_51_32, and it didn't seem to work.  I ended up switching to haml, bypassing this problem.

**Comment by mguterl** [comment]
That was linked off of the downloads page.  

I was editing some Rails views again today and it was stuttering again, sigh...  So this still really isn't fixed.
