### ISSUE TITLE
OrgMode and WindMove keybindings conflict

### ISSUE THREAD

**Issue by jpulakka** [technomancy/emacs-starter-kit#24]
When using OrgMode and WindMove together, shift+arrows keybindings conflict. OrgMode seems to take over then, and jumping from window to window doesn't work as usual, which is quite irritating. What's the policy with emacs-starter-kit -- should it be "fixed out of the box" as suggested at http://www.emacswiki.org/emacs/OrgMode#toc8, or are things like this left to the user?

**Comment by technomancy** [comment]
I dropped windmove in version 2, so this shouldn't be an issue.
