### ISSUE TITLE
More general way to load startup files

### ISSUE THREAD

**Issue by haxney** [technomancy/emacs-starter-kit#26]
Currently, there are a bunch of mode-specific configuration files like `starter-kit-eshell`, `starter-kit-lisp`, `starter-kit-ruby`, etc. As the number of supported modes increases, this setup becomes increasingly unruly.

The solution I used for my `.emacs.d` before migrating to Emacs Starter Kit was to use the function `debian-run-directories` to automatically load all of the files in a given directory, which I had set to `~/.emacs.d/startup`. `debian-run-directories` works by looking for files named `XXfile.el(c)`, where `XX` is a pair of digits. It then loads the files in ascending order, giving you control over the order of file loads without having to manually specify each file.

This allows these startup files to be added and removed without having to keep the `require` statements in sync. I have started to port this change over to ESK (in [my fork](http://github.com/haxney/emacs-starter-kit), on the `dhackney` branch), and was wondering if this is something that seems merge-worthy. It's in a very rough state in my repository right now, so don't take that as representative of what the finished product would look like.

**Comment by technomancy** [comment]
This is actually being addressed in version 2 of the starter kit; each piece of language support is split into a separate package.el entry.
