### ISSUE TITLE
Cannot get to work on OSX

### ISSUE THREAD

**Issue by jasoncwarner** [technomancy/emacs-starter-kit#3]
For some reason I cannot get it to work on OSX. Here is what I have:

/Users/jason/.emacs.d/emacs-starter-kit

I git cloned the emacs-starter-kit to get the directory. I started up emacs (Aqua Emacs) and tried M-x package<tab> and nothing. I tried M-x clojure<tab> and nothing

I am a complete Emacs newbie, so help is appreciated! Thanks!

**Comment by j1n3l0** [comment]
Try copying the contents of emacs-starter-kit to ~/.emacs.d. I think that's what we're supposed to do (worked on Ubuntu 8.10) but it's not explicitly clear in the docs ;0)

**Comment by jasoncwarner** [comment]
I've tried both methods but neither seem to work...

**Comment by j1n3l0** [comment]
I've tried it on Mac OS X 10.4 and it works, so I am sorry I cannot offer any more advice on that issue :0(

**Comment by tss** [comment]
I encountered the same problem as the original poster when I set up the starter kit.  It appears that Aquamacs does not look in .emacs.d/ by default.  If you want something that works out of the box, I recommend downloading from here: http://emacsformacosx.com/

**Comment by technomancy** [comment]
If someone can provide instructions that work for Aquamacs, I will add them to the README. The Starter Kit is designed to work with GNU Emacs though.

**Comment by tss** [comment]
After you've set up .emacs.d/ properly, you can create a one line .emacs file with: (load "~/.emacs.d/init.el").  Maybe in future updates Aquamacs will correctly check in the .emacs.d/ directory, but for now this hack works.

**Comment by tomjack** [comment]
my Aquamacs worked just fine with .emacs.d, no .emacs needed. weird.
