### ISSUE TITLE
Can't find rng-auto.el

### ISSUE THREAD

**Issue by Bluejade** [technomancy/emacs-starter-kit#30]
"Can't find rng-auto.el" thrown while starting Emacs 22 on Ubuntu 9.04 with a new installation of Emacs Starter Kit (downloaded a few minutes ago).

Solved on this setup by using ELPA to install nxml-mode.

**Comment by technomancy** [comment]
Got rid of the bundled nxhtml; seemed to be causing more problems than it solved.
