### ISSUE TITLE
Debugger entered--Lisp error: (void-function yaml-mode)

### ISSUE THREAD

**Issue by Bluejade** [technomancy/emacs-starter-kit#31]
Did a clean download of Emacs Starter Kit on an Ubuntu 9.10 machine with Emacs 23. yaml-mode was correctly auto-installed in ELPA, but I'm getting an error any time I try to open a YAML file. My old Emacs Starter Kit (downloaded on February 18th) worked fine with YAML. I plan to just go back to that for the time being, but thought I should post this issue here. Error follows below:

Debugger entered--Lisp error: (void-function yaml-mode)
  yaml-mode()
  set-auto-mode-0(yaml-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer en.yml> "~/path/to/config/locales/en.yml" nil nil "~/path/to/config/locales/en.yml" (1442241 21))
  find-file-noselect("/home/daniel/path/to/config/locales/en.yml" nil nil)
  ido-file-internal(raise-frame)
  ido-find-file()
  call-interactively(ido-find-file nil nil)

**Comment by technomancy** [comment]
Try M-x regen-autoloads; you may still have some references to the old version around.

**Comment by Bluejade** [comment]
Thank you for the recommendation.

I tried M-x regen-autoloads, but am still getting the same error with yaml files.

**Comment by codification** [comment]
I get the same error, also use Ubuntu (10.04) and I did not have a previous version of yaml-mode or starter-kit before using the most recent starter kit (as of today). My error looks like this:

File mode specification error: (void-function yaml-mode)

**Comment by technomancy** [comment]
Just pushed a workaround to this. It wasn't packaged for elpa correctly, so an autoload was missing.

**Comment by Bluejade** [comment]
Much thanks. Working fine now!
