### ISSUE TITLE
disable idle-highlight

### ISSUE THREAD

**Issue by larsthegeek** [technomancy/emacs-starter-kit#32]
Quick question, how do I disable idle highlight mode?  I realize I can remove/comment out the offending lines in the modes where I don't desire it but I'd like to _not_ edit files that are part of the starter kit to enable easy updating.

Is there a command I can add to my <username>.el file that will disable idle-highlight globally?

Thanks!

**Comment by technomancy** [comment]
Just committed a fix that activates idle-highlight via coding-hook. This way you can just use remove-hook in your own username.el file, so it should be a lot cleaner.

**Comment by larsthegeek** [comment]
Thanks!
