### ISSUE TITLE
gist.el autoloading broken?

### ISSUE THREAD

**Issue by oyvindio** [technomancy/emacs-starter-kit#33]
Running the latest emacs-starter-kit with with emacs 23 on Arch Linux, with gist.el installed from elpa (automatically installed).

When trying to use `M-x gist-region`, I get the following error:
`gist-region: Symbol's value as variable is void: login`.
`gist-region` doesn't even ask for my github login credentials before failing.

However, if i do `M-x load-file path/to/gist.el`, gist-region starts working properly.

**Comment by NakedMoleRatScientist** [comment]
Yeah. I have that problem too.

**Comment by oyvindio** [comment]
This issue  is fixed in gist.el 0.5, which is now in elpa.
