### ISSUE TITLE
Error when opening Emacs: Symbol's value as variable is void: grep-find-ignored-files

### ISSUE THREAD

**Issue by smerritt** [technomancy/emacs-starter-kit#34]
This happens in Emacs 23.1, but not 23.2. It looks like it was introduced in commit 418be9d0f95b755b4c55e8a40a6c26b9da13ce95.

**Comment by bosko** [comment]
Yes this is the commit that causes this error. In my case this error disappears if I disable nxhtml (both on Windows and on Ubuntu). So it looks like it is combination of commit 418be9d and nxhtml.

**Comment by smerritt** [comment]
It's anything that requires grep; nxhtml-mode is sufficient, but not necessary to trigger the bug.

**Comment by technomancy** [comment]
nxhtml has been removed from the starter kit.
