### ISSUE TITLE
lambda in Clojure is "fn", NOT "lambda"

### ISSUE THREAD

**Issue by humanitiesNerd** [technomancy/emacs-starter-kit#35]
Hello people, 

the subjects says it all. In clojure the word "lambda" is shown as a, well, lambda greek letter. But while that's appropriate in Elisp and I think in Lisp and Scheme, it is NOT in Clojure.

In Clojure the intended expression to be shown as the greek letter is "fn"

I found that in "starter-kit-lisp.el" there's a call to "run-coding-hooks" (row 59)

"run-coding-hooks" is in "starter-kit-defuns.el" and one of the hooks taht get run is "pretty-lambdas"

I think that pretty-lambdas should differentiate the case it's in Clojure mode and do accordingly

And I'm eager to see your code to fix this thing, since I'm an Emacs (and Lisp like languages) novice.

Thanks
humanitiesNerd

**Comment by technomancy** [comment]
Just added this; good idea.
