### ISSUE TITLE
Looking for an easy way to incorporate SBCL and other lisps alongside clojure - something seems off

### ISSUE THREAD

**Issue by dedward** [technomancy/emacs-starter-kit#37]
Can't seem to find half the slime- functions that are normally there - I'd like to be able to select which lisp environment to use - any pointers?

**Comment by technomancy** [comment]
I haven't used Common Lisp in years, but I think it's possible. Note that right now only slime and slime-repl have been adapted for package.el; if you want to use some of the other slime-contrib libraries you will have to adapt them yourself or use slime from source.

**Comment by dedward** [comment]
Alright, that points me in the right direction - I expect I'll fork it and see what I can come up with - I've seen the question here and there online, and it's a good learning experience anyway.

Thanks for the quick response (and the starter-kit in general)

**Comment by technomancy** [comment]
Cool. You can look at my fork of slime if you want an example of how to adapt slime libs for package.el.
