### ISSUE TITLE
find-file-in-project is broken on emacs 23.2

### ISSUE THREAD

**Issue by wolverian** [technomancy/emacs-starter-kit#38]
After brew install emacs and moving emacs-starter-kit into place:

```
Compiling file /Users/wolverian/.emacs.d/elpa/find-file-in-project-2.0/find-file-in-project.el at Mon Jul 12 18:36:43 2010
find-file-in-project.el:70:1:Error: Cannot open load file: project-local-variables
```

**Comment by dsisnero** [comment]
I got the same error

**Comment by mguterl** [comment]
I'm seeing the same issue, it looks like this commit: b30f368bf1afbab39a130e8284abba323b34d10d introduced the error.

I fixed it by removing 'find-file-in-project from starter-kit-packages

**Comment by technomancy** [comment]
This is a separate package from the starter kit; if it's still broken feel free to report it on ffip's issues.

**Comment by costa** [comment]
I'm sorry, as far as I understand the starter kit's purpose (a smooth fresh start), this IS an issue.
I've tried the starter kit with a totally fresh install of GNU Emacs 23.3.1 on OSX 10.6.6 and got the same error.

Additionally, when trying to delete ANY package via package-list-packages (like find-file-in-project which is reported installed), I'm getting:
condition-case: Wrong type argument: stringp, ...[ascii + binary junk follows]...

This does NOT happen without the starter kit.
I have no problem doing everything manually, but again, imo, it defies the starter kit's purpose.
Unfortunately, my lisp is poor, but I'll be glad to cooperate if you don't have access to an OSX installation.
