### ISSUE TITLE
Weird issue with pinging.  Pinging position.id (Indonesia)

### ISSUE THREAD

**Issue by mguterl** [technomancy/emacs-starter-kit#39]
When working in a Rails ERB template, when my cursor is on the "." in the middle of @position.id and I press C-x-f it starts "Pinging position.id (Indonesia)" and locks up emacs until it times out.

Any ideas how to stop this behavior?

**Comment by technomancy** [comment]
This is a bug in find-file-at-point. You can set ido-use-filename-at-point to nil to disable it.

**Comment by mguterl** [comment]
Thanks!  I would have never figured that out on my own.

**Comment by ivey** [comment]
If you like find-file-at-point but want to kill the Pinging, you can also set ffap-machine-p-known to 'reject

**Comment by technomancy** [comment]
Thanks; that looks handy.
