### ISSUE TITLE
Unable to "git clone" project using git 1.6.0.4

### ISSUE THREAD

**Issue by jkndrkn** [technomancy/emacs-starter-kit#40]
Hi, here is the error I receive when attempting to "git clone" this project:

Getting pack 2f483ef
which contains 94a9ed0 got fd66aab
got ad92aba
got 8de3d05
got f7d17ed
got 4e64e69
got 4ab0d92
got d9f5744
got ac47c3d
got 854a057
got 1b07a62
got aae3250
got ada2ac9
error: Unable to get pack file http://github.com/technomancy/emacs-starter-kit.git/objects/pack/pack-2f483ef284a8154ca75f1308508e881fdb4ddcaa.pack
transfer closed with 1337627 bytes remaining to read
error: Unable to find 94a9ed0 under http://github.com/technomancy/emacs-starter-kit.git
Cannot obtain needed blob 94a9ed0
while processing commit 6b38e16.
fatal: Fetch failed.

Does anyone else see this issue? Should I be using a newer git?

**Comment by technomancy** [comment]
Going to chalk this up to random github network hiccups.
