### ISSUE TITLE
htmlize and ruby-electric are in elpa

### ISSUE THREAD

**Issue by bartvandendriessche** [technomancy/emacs-starter-kit#42]
Should be fine to remove them from elpa-to-submit and just put them in starter-kit-elpa.el

Cheers

**Comment by technomancy** [comment]
Hmm... I'm not seeing these in elpa yet.

**Comment by bartvandendriessche** [comment]
very strange, they appear just fine for me:
http://imgur.com/Sxx6H.png
http://imgur.com/w88iU.png

**Comment by technomancy** [comment]
It may be that they were installed with M-x package-install-from-buffer and show up because they're installed locally even though they're not on the remote servers yet.

**Comment by akappen** [comment]
Reviewing bugs and saw this one, just wanted to add what I'm seeing.  Using the tromey.com elpa source, I see htmlize 1.37 and ruby-electric 1.1 in the package list.  According to http://tromey.com/elpa/news.html they were added on December 3 and May 16 respectively.
Cheers!

**Comment by technomancy** [comment]
Thanks for the heads up; using this now in v2.
