### ISSUE TITLE
vertical-border color settings

### ISSUE THREAD

**Issue by mattharrison** [technomancy/emacs-starter-kit#44]
starter-kit-misc.el sets vertical-border to white.  This may or may not work out with someone's theme.  Is there a way to refactor settings like these?  I load my color theme in $USER.el then this overrides it.

cheers

**Comment by technomancy** [comment]
Well, if a certain theme needs vertical-border set some way then it should set it. Seems like a bug in the theme. But you can fix it in your user.el.

**Comment by mattharrison** [comment]
Thanks much for the response.

Hmmm, if I comment out your setting then it doesn't override my theme (which is set in user.el).  Am I doing something wrong.

As an aside I'm not sure why starter-kit is changing color settings (if it doesn't change all of them).

**Comment by technomancy** [comment]
It's mostly just changing the color because the default looks pretty bad in 8-color console Emacs.

**Comment by mattharrison** [comment]
I'm confused.  I comment out the code in misc.el and my theme works. 
I uncomment the misc code and put 'message' statements in after the misc.el code and after loading my theme and my theme loads after.  Yet I still get white vertical-border.

I'm pretty sure my theme works, because if I turn it on (again) after starting emacs then the vertical-border goes to the color defined in my theme....

/me scratches head
