### ISSUE TITLE
implementation of pretty lambdas for Clojure

### ISSUE THREAD

**Issue by eschulte** [technomancy/emacs-starter-kit#45]
see
http://github.com/eschulte/emacs-starter-kit/commit/fe0e8bb2768c007667dec8b6cd05c85d1d556e36
-- Eric

**Comment by technomancy** [comment]
Thanks, but [already got one](http://metapython.org/_images/already_got_one.jpg)

http://github.com/technomancy/emacs-starter-kit/blob/master/starter-kit-lisp.el#L59

**Comment by eschulte** [comment]
oh nice, looks like I should track your starter-kit development
