### ISSUE TITLE
 emacs starter kit problem in emacs 23.1 or 23.2 

### ISSUE THREAD

**Issue by tommy24** [technomancy/emacs-starter-kit#46]
Hi,

I found that the starter kit has some problem with emacs 23+. It works
fine in emacs 22.
I am using Ubuntu 9.04 and the kernel version is 2.6.28.7.
The problem is that the file content is not rendered correctly on
screen.
I usually open C files and some syntax is obviously wrong(I didn't modify anything)!! And I can see broken words all over the file.
After I moved the cursor to the wrong words or paragraph, then it
started to refresh and showed the words which should be there. It was
weird enough and I am pretty sure there must be something wrong with
the starter kit. The file rendered correctly after I stopped using the
starter kit. Does anyone have the similar issue? Any hint?
Thanks.

**Comment by ghost** [comment]
Have you added custom files to starter kit?

**Comment by tommy24** [comment]
Thanks for your response.
I think I didn't have this problem yesterday. At first, I installed yasnippet and doremi and color-themes. To this point, everything still worked fine.
Then I tried to enable semantic-mode and some configurations mentioned in cedet tutorial. http://alexott.net/en/writings/emacs-devenv/EmacsCedet.html
I've discovered the problem after then.
So I disabled all of them but the problem still exists.
Then I tried a clean copy of starter kit, but still no luck.
Any idea?

**Comment by tommy24** [comment]
Problem found.
(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
This line caused the bug. After removing this line, the screen is refreshing properly.
I have no idea why this could happen.
I can live with the scroll bar showing on the left though.
I would appreciate if someone could give me some hint for solving this scroll bar issue.
Thanks.

**Comment by technomancy** [comment]
This must be a bug with Emacs; pretty sure it's not a starter kit problem.
