### ISSUE TITLE
color themes not working

### ISSUE THREAD

**Issue by dwwalker** [technomancy/emacs-starter-kit#47]
The only color themes available are color-theme-zenburn, color-theme-twilight, color-theme-standard, color-theme-blackboard.  Other color themes that are installed on my system cannot be used and color-theme-select does not produce a list of themes.

**Comment by gabrielelanaro** [comment]
I confirm this bug on my system

**Comment by gtoast** [comment]
Thirded. Also color-theme is now available in ELPA so it can be taken out of the elpa-to-submit folder.

**Comment by skwrl** [comment]
Are you sure ? I get this error: "Package `color-theme-6.6.0' is unavailable" when trying to install any color theme from elpa. I also noticed that color-theme.el in elpa-to-submit is an older 6.5.2 version.

Color-theme not working seems to be related to it being currently located in loaddefs.el but commented off, and missing from starter-kit-misc.el where is should be mentioned according to documentation.

**Comment by skwrl** [comment]
I got color-theme to work in debian sid by copying color-theme-library.el and color-theme.el provided by debian's emacs-goodies-el package into the starter-kit elpa-to-submit directory and executing M-x regen-autoloads and M-x color-theme-select.

**Comment by namuorg** [comment]
I wrote a blog post explaining how to get around this issue: http://blog.dskang.com/2011/05/14/fixing-the-color-theme-problem-with-the-emacs-starter-kit/

**Comment by MortalCatalyst** [comment]
Interesting yes I cannot get the color theme working. On top of that I looked at dskang's workaround but I have never had a "user.el" file on the three installs I have used emacs-starter-kit with on win7 fedora & now debian. My user file appears to be custom.el

(setq autoload-file (concat dotfiles-dir "loaddefs.el"))
(setq package-user-dir (concat dotfiles-dir "elpa"))
(setq custom-file (concat dotfiles-dir "custom.el")

**Comment by namuorg** [comment]
fiebber: _user_.el should be _your-username_.el, not the literal "user.el"
If you look at the bottom of init.el, you'll see that esk loads a file named _user_.el, _user_ being your actual username. 

``` lisp
;; You can keep system- or user-specific customizations here
(setq system-specific-config (concat dotfiles-dir system-name ".el")
      user-specific-config (concat dotfiles-dir user-login-name ".el")
      user-specific-dir (concat dotfiles-dir user-login-name))
(add-to-list 'load-path user-specific-dir)

(if (file-exists-p system-specific-config) (load system-specific-config))
(if (file-exists-p user-specific-dir)
  (mapc #'load (directory-files user-specific-dir nil ".*el$")))
(if (file-exists-p user-specific-config) (load user-specific-config))
```

**Comment by MortalCatalyst** [comment]
On Fri, Sep 2, 2011 at 12:59 AM, dskang
reply@reply.github.com
wrote:

> fiebber: _user_.el should be _your-username_.el, not the literal "user.el"
> If you look at the bottom of init.el, you'll see that esk loads a file named _user_.el, _user_ being your actual username.

Yes I understand but my user name is Sayth but there is no sayth.el
file. On my Fedora box I also never had a sayth.el. It's not
automatically created for me so should I create a file called that, I
have just been attempting to edit custom.el

Sayth

**Comment by namuorg** [comment]
I'm moving this conversation offline as this isn't pertinent to this issue thread.

**Comment by technomancy** [comment]
Version 2 of the starter kit uses these themes straight off marmalade. I believe the autoloads are still screwed up, but this will need to be fixed upstream.
