### ISSUE TITLE
Void variable: paredit-space-for-delimiter-predicates

### ISSUE THREAD

**Issue by jrhorn424** [technomancy/emacs-starter-kit#49]
I receive the following backtrace when starting emacs after a recent pull:
           debug(error (void-variable paredit-space-for-delimiter-predicates))
          add-to-list(paredit-space-for-delimiter-predicates esk-space-for-delimiter\?)
          provide(paredit)
          byte-code("\300 \210\301 \210\302 \210\303\304!\207" [paredit-define-keys paredit-annotate-mode-with-examples paredit-annotate-functions-with-examples provide paredit] 2)
          (paredit-mode t)
          turn-on-paredit()
          run-hooks(emacs-lisp-mode-hook)
          apply(run-hooks emacs-lisp-mode-hook)
          run-mode-hooks(emacs-lisp-mode-hook)
          emacs-lisp-mode()
          set-auto-mode-0(emacs-lisp-mode nil)
          set-auto-mode()
          normal-mode(t)

Aquamacs 2.1 (emacs 23.2.50.1) on Mac OS X 10.6.5

**Comment by bosko** [comment]
Do you have installed paredit from Elpa? I had it and after removing it this error disappeared. Paredit is now put in elpa-to-submit and obviously it mixing these two lead to this error.

**Comment by technomancy** [comment]
Yes, this is from having an old paredit installed; bumping to the latest will fix it.

**Comment by jrhorn424** [comment]
Thanks bosko. Tehcno, are you recommending uninstalling it and downloading the source, manually activating it, etc?

**Comment by jrhorn424** [comment]
Thanks. Issue resolved.
