### ISSUE TITLE
suggestion: change key binding for 'menu-bar-mode

### ISSUE THREAD

**Issue by sinewalker** [technomancy/emacs-starter-kit#5]
the <f1> key binding overwrites the default Emacs f1 help prefix, which is widely documented in a lot of the sources that are read by Emacs noobs.

perhaps change this binding to M-f10:  the F10 key traditionally accesses the menus on GUIs like Windows and Mac, as well as older TUIs like DOS (Turbo Vision derivatives). It is likely this key binding will be familiar, and just as memorable as F1.
# Here's a patch:

--- starter-kit-bindings.el (revision 2)

+++ starter-kit-bindings.el (working copy)

@@ -15,7 +15,7 @@

 (global-set-key (kbd "C-c n") 'cleanup-buffer)

 ;; Turn on the menu bar for exploring new modes
-(global-set-key [f1] 'menu-bar-mode)
+(global-set-key [(meta f10)] 'menu-bar-mode)

 ;; Font size
 (define-key global-map (kbd "C-+") 'text-scale-increase)

**Comment by technomancy** [comment]
Good point. I've bound it to C-f10 since my WM binds M-f10 already. I had forgotten that F1 was mentioned in the Emacs docs.
