### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by scgilardi** [technomancy/emacs-starter-kit#51]
on a mac, I moved my previous .emacs.d to .emacs.d.save and fired up emacs 24.0.50 in iTerm. Emacs came up completely vanilla. I pasted the addition of the technomancy archive into the _scratch_ buffer and executed each line. Then I tried M-x package-install RET starter-kit RET and got a beep and an indication there is no such package. Then I tried M-x package-list-packages and elk v2.0 was there. I installed it, but at the end of the compilation got the message "Symbol's value as variable is void: esk-system-name". Now when I start up emacs I get that same message.

**Comment by technomancy** [comment]
> Then I tried M-x package-install RET starter-kit RET and got a beep and an indication there is no such package.

This is a bug in package.el; it's definitely on my list. I need to reword the readme until it's fixed though.

The esk-system-name thing is a bug where you'd have the system-name variable report as the FQDN rather than the host name on OS X. If it's fixed in Emacs 24 then I'd like to just remove that workaround entirely. Otherwise I just need to re-order it. Just let me know.

thanks.

**Comment by dakrone** [comment]
This bug still occurs with the latest emacs 24 built from source, you mentioned rewording the readme, is there a workaround to use in the meantime before this bug is fixed?

**Comment by technomancy** [comment]
You can use M-x package-list-from-packages to install the starter kit in the mean time.

**Comment by technomancy** [comment]
I think the docs are clearer about needing to refresh manually now. But I'll still file this upstream.

**Comment by thefonso** [comment]
Having trouble doing the installation...using 24....does this exist inside the normal Packages installation system?

**Comment by thefonso** [comment]
Never mind just found it....I'll update if all goes well.

**Comment by thefonso** [comment]
Ok installation seems to have gone well. I'll post if I have any problems.
