### ISSUE TITLE
Window management

### ISSUE THREAD

**Issue by aguynamedben** [technomancy/emacs-starter-kit#52]
Hey, is there any window management niceness in the emacs-starter-kit?  I am looking for a better way to manage 3 vertically split windows than C-x } and {.  The other day I found via Google a chord involving the equals sign (=) that equally sized the windows, but I can't find it for the life of me.

I tried adding http://www.emacswiki.org/emacs/WindowResize and http://www.emacswiki.org/emacs/GrowShrinkWindows, but they either didn't work or had a parenthesis balance error.

What do you all use to resize windows?

**Comment by colbell** [comment]
http://lifealgorithms.wordpress.com/2009/12/02/adjusting-resizing-buffer-size-from-keyboard/

**Comment by technomancy** [comment]
I've heard good things about [Workgroups for Windows](https://github.com/tlh/workgroups.el)

**Comment by aguynamedben** [comment]
Thanks for the feedback.  I posted this back when I was more n00bish.  My solution was finding C-x +.  I usually split 3 windows vertically on my 24" monitor.  Thanks again, I'll check those other things out!

-Ben
