### ISSUE TITLE
How to type Javascript

### ISSUE THREAD

**Issue by pbevin** [technomancy/emacs-starter-kit#53]
In Espresso mode, when I type "function()", the "function" turns into a florin sign, and the point is left between the n and c of function, so that when I then type SPC, I'm left with

  $(fun ction()

What's the Emacs Way here? Should I retrain my fingers to type "f u n c t i o n ( ) C-e SPC"?

**Comment by technomancy** [comment]
This is actually just a render-time hack to combat the verbosity inherent in Javascript. Your files on disk contain the full "function" text. This is explained in the new FAQ:

https://github.com/technomancy/emacs-starter-kit/commit/73135b60cee7e9983e312e3af5da5de0136aead4#L0R56

**Comment by pbevin** [comment]
Thanks for a quick answer. I understand why the word "function" gets replaced. My question was about the next three keystrokes.  The point ends up in the wrong place after I type "()", so that when I type SPC, the space separates the n and c in "function".  Is this intended behavior?

**Comment by technomancy** [comment]
Oh, I see. No, that's a bug; it's tracked in #7.
