### ISSUE TITLE
Ruby 1.9 syntax broken when using rvm

### ISSUE THREAD

**Issue by kunzmann** [technomancy/emacs-starter-kit#54]
I was able to work around this by pasting in the path to my rvm ruby 1.9 to flymake-ruby-init in starter-kit-ruby.el

I'd love to know a better solution, though.

**Comment by technomancy** [comment]
It could be that you're hitting the OS X bug that ignores your .profile for all applications launched from the GUI. But really I'm not sure; I haven't used Ruby in a few years. I could use some help maintaining the Ruby support in the Starter Kit; I'm not really qualified to do so any more.
