### ISSUE TITLE
[v2] Starter-kit language-specific packages are not available from technomancy.us

### ISSUE THREAD

**Issue by haxney** [technomancy/emacs-starter-kit#55]
I'm really liking the new package-ized starter-kit, but I noticed that the contents of the folder `language` in the repo are not included in either the `starter-kit-2.0.tar` package or as individual packages on technomancy.us.

**Comment by technomancy** [comment]
Yeah, I am still working on packaging the language-specific parts. I want them to be treated as separate packages since most people won't be using all of them. I hope to have them up in the next few days; in the mean time there's M-x package-install-from-buffer.

**Comment by haxney** [comment]
Cool, thanks. I'll use `package-install-from-buffer` for now.

**Comment by technomancy** [comment]
I have everything but the perl one up on repo.technomancy.us now, though I will probably move to http://marmalade-repo.org eventually.
