### ISSUE TITLE
[v2] Binding "C-c C-x" for execute-extended-command interferes with other bindings

### ISSUE THREAD

**Issue by haxney** [technomancy/emacs-starter-kit#56]
Org-mode uses the prefix `C-c C-x` for a bunch of stuff, so setting it to `execute-extended-command` will cause it to be shadowed when in org-mode.

Somewhat related, I set a global binding for `C-c C-x C-o` (for `org-clock-out`), causing problems during startup. It complains that "Key sequence C-c C-x C-o starts with non-prefix key C-c C-x". I am just globally defining a binding which already exists in org-mode (with my own modification), so conflicting like this would seem to be a problem.

For what it's worth, I have used `C-x C-m` as my replacement `M-x` (actually `smex`), so that would be a possible substitute for `C-c C-x`.

**Comment by milkypostman** [comment]
I'm not sure how to get this to work either.  I tried putting this rebinding in the `eval-after-load` after the starter-kit-bindings gets loaded but didn't work.  maybe there is a hook somewhere.

**Comment by technomancy** [comment]
Right now the use of autoloads in bindings.el makes it difficult to customize since the call to provide is never triggered. I'll look into adding a hook to expose the proper override placement.

C-x C-m sounds good for extended-command.

**Comment by milkypostman** [comment]
I don't know if this got relayed, but you can put these bindings in the end of `init.el` and it works fine.  You just have to make sure that ELPA gets loaded first then there is no issue.
