### ISSUE TITLE
find-file remapped to ido-find-file prevents creation of new files that match via ido

### ISSUE THREAD

**Issue by ismarc** [technomancy/emacs-starter-kit#58]
Given filename MyTestSubFile.c exists, if you use C-xC-f and in the same directory enter the filename MyTestFile.c, ido will open MyTestSubFile.c rather than visiting a new file.  In order to work around this, in my user.el I added the following:
    (global-set-key "\C-c\C-f" (lambda (filename)
                                 (interactive "FFind file: ")
                                 (switch-to-buffer (find-file-noselect filename))))

This basically reimplements find-file (and is a bit of a kludge), but allows me to fall back to traditional emacs style file visiting should ido put up a fight.

**Comment by technomancy** [comment]
This is actually covered in the FAQ in the v2 branch: https://github.com/technomancy/emacs-starter-kit/blob/v2/README.markdown

**Comment by ismarc** [comment]
That covers it beautifully.
