### ISSUE TITLE
starter-kit-misc.el tries to set a face that no longer exists

### ISSUE THREAD

**Issue by bartvandendriessche** [technomancy/emacs-starter-kit#6]
I'm fairly new to emacs, so i might be mistaken here, but after merging my fork with your current head, I was getting errors trying to open files with mumamo mode.

Basically it would say that there was no face named 'mumamo-background-chunk-submode'.

I resolved the issue by editing the starter-kit-misc.el file and setting 'mumamo-background-chunk-submode1' instead of 'mumamo-background-chunk-submode'.

Seems like the new nxhtml splits out 'mumamo-background-chunk-submode' into 4 different chunk-submodes now.

**Comment by technomancy** [comment]
Thanks for this catch; seems like the upgrade to nxhtml-mode changed the load order of nxhtml and mumamo.
