### ISSUE TITLE
find-file-in-project references void variable: ffip-patterns

### ISSUE THREAD

**Issue by sfllaw** [technomancy/emacs-starter-kit#62]
Running `M-x find-file-in project` fails with:
    provide: Symbol's value as variable is void: ffip-patterns

This is because ELPA only has find-file-in-project 2.0 and it looks like `ffip-patterns` is new in 2.1.

**Comment by ghost** [comment]
It looks like find-file-in-project 2.1 has been pushed up to marmalade:

http://marmalade-repo.org/packages/find-file-in-project

So if you upgrade to this version of find-file-in-project, it should be taken care of.  Thanks to abedra and technomancy during Refactotum at RailsConf 2011 for helping find the solution to this issue.

**Comment by sfllaw** [comment]
I assume that Marmalade is the new package ELPA in ESK? If so, this bug can be closed.

**Comment by ghost** [comment]
Right, it was changed here (I didn't notice this when I first looked at this issue):

https://github.com/technomancy/emacs-starter-kit/commit/f317a2c318542e884b63a9069e74c4a32970ae6a#init.el
