### ISSUE TITLE
Do Not Mess With People's Toolbars and Menubars!

### ISSUE THREAD

**Issue by haziz** [technomancy/emacs-starter-kit#67]
Do not mess with people's toolbars and menubars! I do not care as much about the scrollbar but did restore that as well. It took me over an hour to figure out what happened, and to restore the toolbar, menubar and scrollbar. I got your init.el file after it was recommended on the Peepcode screencast. As a near total newbie it took me quite a while to figure out the details and to comment out the offending three lines of code, fortunately they were on top in the init.el file. Sorry, in reference to your comment in the init.el file, I do not trust you on this one.

BTW I am using emacs mainly for developing in C and as a general text editor and script editor. Will I see any benefit from these customizations? They seem to be oriented more towards other languages.

Also I intend to use Mercurial rather than Git as my version control set-up within emacs. Will your customizations influence that?

Sincerely,

Hany.

**Comment by technomancy** [comment]
Yeah, if you are using mercurial with C and shell scripts and have strong opinions about GUIs, the starter kit might not be right for you.
