### ISSUE TITLE
Espresso+paredit do odd things when defining a new js function

### ISSUE THREAD

**Issue by dgoodlad** [technomancy/emacs-starter-kit#7]
I'm trying to type the following:

var foo = function(bar) {
  return null;
}

When I open the first parenthesis, 'function (' is prettified with the fn symbol: that's fine.

When I type the closing parenthesis after bar, it highlights the left-paren briefly, then opens a newline automatically. ???

When I type the open brace, I can't indent the next line with the return statement. ???

When I type the closing brace, it automatically moves it up onto the same line as the return statement, with not even a space between it and the semicolon. ???

I've tried commenting out the code block that prettifies the 'function' keyword, which helps a little but now insists on inserting a space between 'function' and the left-paren.

**Comment by seth** [comment]
You might just try M-x paredit-mode (to turn OFF paredit).  I find paredit's notion of what javascript code should look like to be exceedingly annoying, wrong, and frustrating to use.  Also, I don't like it much.

**Comment by adamcohen** [comment]
I'm having a similar issue. If I type the following as the last line in a file:

jQuery(document).ready(function 

when I try to type the next open parenthesis, it gives me an error: "Point 455 after end of properties" and I can't type anything else.  It works fine if the function has some new lines after it, but if it's the last line in the file, it stops working properly.  This is really quite annoying - anyone know how to fix this other than turning off paredit-mode?

**Comment by yevgenko** [comment]
also freezing emacs when occurs in *.erb

**UPDATE:** oops, my problem only happen with nxhtml enabled and editing something like test.conf.erb or test.vcl.erb, etc., seems not related to current issue, sorry :)

**Comment by technomancy** [comment]
Is it any better with the latest paredit?

**Comment by sunny36** [comment]
Seems to be better with the newer paredit.

**Comment by technomancy** [comment]
Great; closing.
