### ISSUE TITLE
Error in init file: error: "Unknown keyword :risky"

### ISSUE THREAD

**Issue by panzerneo** [technomancy/emacs-starter-kit#70]
Just cloned this proj into my .emacs.d and launched emacs from the Terminal in OS X.

**Comment by technomancy** [comment]
What Emacs version does this happen under?

**Comment by ramen** [comment]
I get this error in Emacs 22. It comes from package.el. I usually upgrade Emacs when it happens.

**Comment by technomancy** [comment]
I'm on the edge as to whether Emacs 22 should still be supported by the starter kit. Version 2 will require Emacs 24, and I strongly suggest upgrading to 23 for those on version 1.

**Comment by ghost** [comment]
Correct, I ran an updated Mac OSX but it comes default with emacs 22. Sorry about that miss.

**Comment by technomancy** [comment]
OK, I'm going to just bite the bullet and drop support for 22.

**Comment by jasonmp85** [comment]
Wanted to point out that the README still says 22 is supported.
