### ISSUE TITLE
disabling menubar as default is in direct contradiction of the screencast advice

### ISSUE THREAD

**Issue by skwrl** [technomancy/emacs-starter-kit#71]
This default parameter contradicts the peepcode's screencast which encourages to use menus as a reference to learn the keys. This is not definitely not beginners friendly.

**Comment by antage** [comment]
I completly agree.

**Comment by technomancy** [comment]
The advice is to turn the menubar on while you're learning, which implies keeping it off when you're not. That's why it's bound to C-f10.

**Comment by skwrl** [comment]
That's exactly my point. 

What I'm arguing here is that the default setting should be consistent with the screencast, and newcomer friendly as a starter kit is  targeted towards newcomers. One first start by learning, hence require the menu, and doesn't get into fiddling with init files until some progress has been made thus preventing the targeted audience of newcomers from enabling the menu, in turn increasing their frustration and confusion and maybe even driving them away.

Emacs already has a steep learning, there's no need to add to it.

As a moderately experienced emacs user, after switching to the starter-kit I have been annoyed by the absence of menu as I'm in the middle of the learning process and use it as a reference tool on a regular basis. I happened to find where it was disabled while looking for a mysterious that made my previously working color theme unavailable and color-theme-initialize undefined. I was able to turn it back on but still I got put off by the comment that contradicts the screencast, imho it is an awful way of putting it. 

I ended up removing the starter-kit altogether as from the first look it appears to be partially broken (color-theme isn't functional), partially outdated (color-theme is lagging 2 revisions behind the stable version released 2 years ago !!) and is inconsistent with the screencast. 

This version is not suitable for me so I'll try my luck with one of the many forks, hopefully one of those will be updated and working out of the box. Thanks anyways.

**Comment by gmcclure** [comment]
Worked out of the box for me.

I don't think of a starter kit as necessarily being targeted at beginners. That would be a Beginner's Kit. And while the documentation asserts that this project was _originally_ intended for beginners, I think it's right to think of any starter's kit as a reasonable set of initial choices and a way to avoid tracking down the associated packages and connecting all the wires yourself. I've been using Emacs, on and off, for six years, and I still appreciate what's been done with this project. It's smart and useful.

As a moderately experienced Emacs user, why not just turn on the menu yourself? Wouldn't that have taken far less time than writing a critical message to someone who's providing software for free?

**Comment by skwrl** [comment]
It's not just about me and my own usage, I think about others users too, especially beginners. Beginners are the building blocks of new generations of users and experts, and as such should be treasured. The mixed signals I got from the emacs-starter-kit screencast / literature and actual kit proved to be a disappointment to me and would most certainly affect a total beginner in a negative way.

imho, software is about users, and user feedback is a vital component of software solutions, personal assumptions we make as developers often turns out not fitting users so well. I consider emacs-starter-kit a worthy project and thought I should provide [feedback](http://meatballwiki.org/wiki/CriticismIsFeedback) from my own knowledge and experience with it.

It is my personal belief that it is better to speak and risk passing for an idiotic moron than let it slip and miss an opportunity of improvement.
