### ISSUE TITLE
Update elpa-to-submit

### ISSUE THREAD

**Issue by bartvandendriessche** [technomancy/emacs-starter-kit#79]
There are a bunch of packages in your elpa-to-submit directory that have been added to elpa by now.

More specifically, the following packages are now available through elpa:

notify
oddmuse
paredit
scpaste
color-theme

Its ok to remove those from elpa-to-submit and just add them to starter-kit-elpa.el

**Comment by technomancy** [comment]
Thanks, but I'm doing active development work on the v2 branch, where this doesn't apply, so right now I'd rather hold off on changes to master. See https://github.com/technomancy/emacs-starter-kit/commit/55fb2cbb73aa4e605f09a487e11462db2019f025
