### ISSUE TITLE
Curly brace no longer "auto-closes" in clojure with Paredit

### ISSUE THREAD

**Issue by sethtrain** [technomancy/emacs-starter-kit#8]

**Comment by technomancy** [comment]
Can you provide more details? It works for me.

**Comment by sethtrain** [comment]
Maybe it is how i set up clojure, i don't use the clojure-install or whatever; i download the files into a separate directory (http://github.com/sethtrain/emacs-starter-kit/blob/57a83d6598ca52614cef8cfc4c74b0b4bf457cbb/seth/clojure.el) but it does still break for me.  When I am in a .clj file the "(" auto-closes but the "{" doesn't and it did a couple days ago.

**Comment by sethtrain** [comment]
Looks like this has to do with the version of paredit.  When I look at the clojure library it is setup to use the curly brace "auto close" for paredit >= 21 and the version that is in elpa is 20.  When removing that it works but that is always downloaded when I restart emacs.

**Comment by sethtrain** [comment]
I have fixed this, it can be found at: http://github.com/sethtrain/emacs-starter-kit

**Comment by technomancy** [comment]
I'm slow; just merged the patch.
