### ISSUE TITLE
v2: $USER.el loads after init.el

### ISSUE THREAD

**Issue by foogoof** [technomancy/emacs-starter-kit#84]
;; init.el
(prin1 "init")

;; foogoof.el
(prin1 "foo")

From _messages_

Loading /Users/foogoof/.recentf...done
Cleaning up the recentf list...done (0 removed)
Ido mode enabled
Loading /Users/foogoof/.emacs.d/foogoof.el (source)...
"foo"
Loading /Users/foogoof/.emacs.d/foogoof.el (source)...done
"init"

**Comment by filipeamoreira** [comment]
Hi @seth-schroeder,

You probably meant that $USER.el load **before** init.el. On my setup my local user configurations load before init.el and is overwritten by the default package.el installation.

**Comment by technomancy** [comment]
I think now with the way autoloads work in version 2 this is out of our control.
