### ISSUE TITLE
Make it possible to disable magit-simple-keys

### ISSUE THREAD

**Issue by plathrop** [technomancy/emacs-starter-kit#86]
Since magit-simple-keys is now required by the starter kit packages, and there is no way within magit-simple-keys to disable its functionality, the starter kit should provide a way to disable magit-simple-keys for those of us who prefer the standard magit keybindings, but want to use the rest of the starter kit.

**Comment by plathrop** [comment]
I really hope I'm not just a big idiot who is missing some obvious way to disable it! :-)

**Comment by technomancy** [comment]
Fixed in 2.0.2; you should be set.
