### ISSUE TITLE
dired does not find ls or df on OS X 10.7

### ISSUE THREAD

**Issue by jasonblewis** [technomancy/emacs-starter-kit#87]
if you try and run dired on emacs on OS X 10.7 you get the following error:

dired-insert-directory: Searching for program: No such file or directory, ls

i have tested this in v1 and v2 and i get the same error.

not sure how to debug but happy to help if you can guide me

GNU Emacs 24.0.50.1 (x86_64-apple-darwin, NS apple-appkit-1038.35) of 2011-06-13 on virtualmac.porkrind.org

**Comment by technomancy** [comment]
Sorry, this isn't related to the starter kit. I'm not sure how to debug since I don't have a Mac.
