### ISSUE TITLE
[Request] Integrating smex into ESK

### ISSUE THREAD

**Issue by ghost** [technomancy/emacs-starter-kit#88]
Hello, thank you very much for your job supporting this nice piece of software. I was wondering if you could include [smex](http://www.emacswiki.org/emacs/Smex) into your distribution? Smex is like IDO for commands, which is really cool and easy to use. 

Cheers.

**Comment by technomancy** [comment]
I used smex for a while, but then I found some code to make ido work everywhere, not just in M-x, so I am going to integrate that into the next release: https://github.com/technomancy/ido-ubiquitous

This covers everything I was using smex for, but it appears smex has a few other features as well. Do you think they're enough to justify including two possibly-redundant libraries?

**Comment by ghost** [comment]
> I used smex for a while, but then I found some code to make ido work everywhere, not just in M-x

Well this sounds really cool and exciting.

> so I am going to integrate that into the next release

Awesome!

> Do you think they're enough to justify including two possibly-redundant libraries?

Well, I am not sure I don't think a couple of obscure features would be used by the majority of people. But it's your configuration file, after all ;)

Cheers.

**Comment by technomancy** [comment]
So it turns out the sorting by history is something really valuable that smex provides over ido-ubiquitous, so version 2.0.2 pulls in both.

**Comment by DarwinAwardWinner** [comment]
Incidentally, I should point out that ido-ubiquitous doesn't actually work for M-x. Just everything else. So you still need smex no matter what. Also, sorting by history is crazy awesome.
