### ISSUE TITLE
Move the directory containing this file to ~/.emacs.d (If you already have a directory at ~/.emacs.d move it out of the way and put this there instead.)

### ISSUE THREAD

**Issue by gaffo** [technomancy/emacs-starter-kit#89]
That is not an installation instruction. Move what WHERE? put an effing command line that I can copy paste in there. Stop being an emacs guy and assuming that I know wtf you are talking about.

**Comment by technomancy** [comment]
This no longer applies with version 2 of the starter kit. Just switched the default branch to v2, so this shouldn't be an issue anymore.

**Comment by gaffo** [comment]
better. got it to work. it might be nice to put "git clone https://github.com/technomancy/emacs-starter-kit .emacs.d" and a emacs them directly into init.el or wget / echo it in.
