### ISSUE TITLE
Symbols function is void: paredit-open-curly

### ISSUE THREAD

**Issue by jsmestad** [technomancy/emacs-starter-kit#9]
Running into the following problem, opening up an application.js file.. than I try to type

jQuery(document).ready(function($)

then the minute I try to type { it returns "Symbols function is void: paredit-open-curly". This is the same problem I had prior to the brace -> curly change. This also happens when I try to use } but the error is then regarding paredit-close-curly-and-newline.

**Comment by HashNuke** [comment]
This can be solved. You need to comment out the 'eval-after-load' code block in starter-kit-js.el in your .emacs.d dir and it works fine later but you'll get some worse bugs like not being able to delete the flower braces etc.

so the solution is to open up the init.el file and then delete the line require('starter-kit-js.el) and delete the starter-kit-js.el file too and just create an espresso.el file and use the contents from here http://svn.savannah.gnu.org/viewvc/*checkout*/espresso/espresso.el?revision=210&root=espresso and restart emacs to get it working. (just use the latest espresso.el file from the svn)

P.S: Thanks to skorpan and daleharvey

**Comment by technomancy** [comment]
This shouldn't be an issue with the latest paredit.
