### ISSUE TITLE
plist-to-alist

### ISSUE THREAD

**Issue by joegallo** [technomancy/emacs-starter-kit#90]
Warning (initialization): An error occurred while loading `/home/joegallo/.emacs.d/init.el':                                                                                                                                                  

Symbol's function definition is void: plist-to-alist                                                                                                                                                                                          

To ensure normal operation, you should investigate and remove the  
cause of the error in your initialization file.  Start Emacs with  
the `--debug-init' option to view a complete error backtrace.                                                                                                                                                                                 

---

I get the above stacktrace when I try to use the starter kit with emacs from git.  I'm guessing the problem is that that function is being referenced at line 261 of elpa-to-submit/color-theme.el.  Any ideas why this works just fine in emacs 23 but doesn't on emacs git?

**Comment by joegallo** [comment]
for now i've worked around this by just deleting the offending lines of the cond.

**Comment by technomancy** [comment]
Recommend using color-theme from marmalade; seems to be fixed there.

**Comment by xingxing** [comment]
Hi, If you are using XEamcs, maybe you should add to your .emacs:
(setq default-frame-alist
      '((top . 100) (left . 100)
    ))
