### ISSUE TITLE
emacs 24: typo in the README?

### ISSUE THREAD

**Issue by denlab** [technomancy/emacs-starter-kit#91]
"You'll need Emacs 24", you mean 23 ?

**Comment by technomancy** [comment]
Nope, version 2 of the starter kit requires Emacs 24. I'll add a note about using version 1 for Emacs 23 support.

**Comment by denlab** [comment]
OK, it wasn't obvious either from the pre-built binaries sites you mention or the official Emacs sites that the latest "nightly build" was Emacs 24. Thanks
