### ISSUE TITLE
emacs 24 for os x? 

### ISSUE THREAD

**Issue by djpenton** [technomancy/emacs-starter-kit#92]
The link to precompiled emacs for OS X does not offer emacs 24, as far as I can see.

Why does the starter kit require v.24? Is 24 not an unstable version?

**Comment by fracek** [comment]
> The link to precompiled emacs for OS X does not offer emacs 24, as far as I can see.

You have to download the nightlies to have Emacs 24, you can find them after releases and pretests.

**Comment by djpenton** [comment]
Sent from my iPad

On 2011-09-22, at 9:49 AM, Francesco Ceccon
reply@reply.github.com
wrote:

> > The link to precompiled emacs for OS X does not offer emacs 24, as far as I can see.
> 
> You have to download the nightlies to have Emacs 24, you can find them after releases and pretests.

I have no idea what that means.

**Comment by fracek** [comment]
> I have no idea what that means.

Go to http://emacsformacosx.com/builds , scroll down to the section named "Nightlies" and download the latest build, that is GNU Emacs 24.0.50.1

**Comment by djpenton** [comment]
Thanks!

And sorry for being abrupt in my last post.
- Jake -

On 2011-09-22, at 10:14 AM, Francesco Ceccon
reply@reply.github.com
wrote:

**Comment by technomancy** [comment]
I think it's clearer now that 24 has gone into pretest.
