### ISSUE TITLE
add highlight-parentheses-mode for clojure

### ISSUE THREAD

**Issue by srid** [technomancy/emacs-starter-kit#93]
I had to do this:

<pre>
;; parentheses friendly
;; http://stackoverflow.com/questions/2413047/
(add-hook 'clojure-mode-hook 'highlight-parentheses-mode)
(setq hl-paren-colors
      '(;"#8f8f8f" ; this comes from Zenburn
                   ; and I guess I'll try to make the far-outer parens look like this
        "orange1" "yellow1" "greenyellow" "green1"
        "springgreen1" "cyan1" "slateblue1" "magenta1" "purple"))
</pre>

**Comment by dgutov** [comment]
I don't think this should be added. Not everyone likes the explosion of colors.
For the purposes of paren-matching, we already have paredit.

**Comment by srid** [comment]
Fair enough.
