### ISSUE TITLE
starter-kit-ruby in package system broken

### ISSUE THREAD

**Issue by ddoherty03** [technomancy/emacs-starter-kit#99]
I get a void function error on opening any ruby file for the function esk-run-coding-hook after installing esk from the 
package facility in Emacs 24.  Looks like the 2.0 version listed is out of date and incompatible with the other files in the starter-kit.

I'm not sure whether the packages are coming from ELPA or marmalade, but I think ELPA.

Is this the right place for this issuer, or elsewhare.

**Comment by technomancy** [comment]
The ruby module for the starter kit is currently looking for a maintainer, so I'm afraid this won't be addressed until someone steps up.

**Comment by chrislo** [comment]
A work-around is to add (remove-hook 'ruby-mode-hook 'esk-run-coding-hook) to your own config. It'd be great to see a maintainer for the ruby packages, but sadly I don't think my elisp is up to the job!

**Comment by smerritt** [comment]
New starter-kit-ruby maintainer here.

I've just pushed 2.0.1 to Marmalade, which I believe will fix this problem. (It's got others, but I haven't gotten there yet.)

**Comment by dakrone** [comment]
starter-kit-ruby 2.0.1 depends on ruby-mode 1.1, which is not available in marmalade repo. It currently complains about "Package `ruby-mode-1.1' is unavailable" when attempting starter-kit-ruby 2.0.1 installation.

(just so you guys know)

**Comment by smerritt** [comment]
This one's interesting.

starter-kit-ruby depends on inf-ruby 2.2.1.

inf-ruby 2.2.1 depends on ruby-mode 1.1, which does not exist on Marmalade or anywhere useful.

inf-ruby 2.2.2 fixes these things, but hasn't been released because the maintainer lost his password (https://github.com/nonsequitur/inf-ruby/issues/4).

The inf-ruby maintainer can't reset his password because Marmalade's password-reset API is busted (http://code.google.com/p/marmalade/issues/detail?id=26).

Rather than shave this yak, I think I will just cut inf-ruby out of starter-kit-ruby until such time as inf-ruby works again.

**Comment by smerritt** [comment]
I was wrong earlier: ruby-mode 1.1 does not exist on Marmalade, but it does exist on tromey.com.

Try adding this to your init.el: 

```
(add-to-list 'package-archives '("tromey" . "http://tromey.com/elpa/") t)
```

That'll get you ruby-mode 1.1, which will get you moving again.

inf-ruby isn't the only thing that depends on ruby-mode 1.1, either. Notably, rinari depends on ruby-mode 1.1, so you'll need to add tromey to your package sources to use rinari.

I think the answer to this one may just be to document that users of starter-kit-ruby need to have tromey as a package source.

Thoughts?

**Comment by technomancy** [comment]
That works all right as a short term solution, but we should probably badger the hell out of the marmalade maintainer to get this guy's password reset, because having him locked out is just ridiculous.

**Comment by smerritt** [comment]
Agreed. I'll take a look at the Marmalade source and see how hard it would be to fix the password-reset-email problem. In the meantime, I'll add a note to the README.

**Comment by nonsequitur** [comment]
I'm finally back on Marmalade!
With the [latest inf-ruby release](http://marmalade-repo.org/packages/inf-ruby/2.2.3) all tromey.com/elpa dependencies can be removed.
([Here's my pull request](https://github.com/technomancy/emacs-starter-kit/pull/118))

**Comment by bmabey** [comment]
The fixes appear to all be done (thanks @nonsequitur), but marlade still has an [old version (2.0.1)](http://marmalade-repo.org/packages/starter-kit-ruby).  @smerritt, would you mind pushing 2.0.2 to marmalade?

**Comment by smerritt** [comment]
Done.
